//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I6AOAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_A2A0BC_i6aoEntities : DbContext
    {
        public DB_A2A0BC_i6aoEntities()
            : base("name=DB_A2A0BC_i6aoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Student> Students { get; set; }
    
        public virtual ObjectResult<getStudentInfo_Result> getStudentInfo(string sTDNR, string cODE)
        {
            var sTDNRParameter = sTDNR != null ?
                new ObjectParameter("STDNR", sTDNR) :
                new ObjectParameter("STDNR", typeof(string));
    
            var cODEParameter = cODE != null ?
                new ObjectParameter("CODE", cODE) :
                new ObjectParameter("CODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getStudentInfo_Result>("getStudentInfo", sTDNRParameter, cODEParameter);
        }
    
        public virtual ObjectResult<getStudentsByClass_Result> getStudentsByClass(string cLASS)
        {
            var cLASSParameter = cLASS != null ?
                new ObjectParameter("CLASS", cLASS) :
                new ObjectParameter("CLASS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getStudentsByClass_Result>("getStudentsByClass", cLASSParameter);
        }
    }
}
